version: '3.4'

services:
    catalogdb:
        image: mongo

    basketdb:
        image: redis:alpine

    catalog.api:
        image: ${DOCKER_REGISTRY-}catalogapi
        build:
            context: .
            dockerfile: src/Catalog.Api/Dockerfile

    basket.api:
        image: ${DOCKER_REGISTRY-}basketapi
        build:
            context: .
            dockerfile: src/Basket.Api/Dockerfile

volumes:
    mongo_data:
    